### PR TITLE
change port from int16 to uint16

### PR DESCRIPTION
**Pull request by deoxxa**
Does precisely what it says. Ports above 32767 don't fit in an `int16` so I changed it to `uint16`.

### CODE REVIEW

**Comment by torrance** [comment]
Cheers - I'm not actively developing this but happy to accept the pull request nonetheless. :)

**Comment by deoxxa** [comment]
Oh, well I'd be happy to pick things up if you like! I'm currently going through and adding all the bits and pieces to make this work to some degree. I'm planning to use it for fetching metainfo data from peers via [BEP9](http://www.bittorrent.org/beps/bep_0009.html), so I'm going to wire it up to the DHT and all that fun stuff. Are you interested in receiving pull requests for the features I'm adding?

**Comment by torrance** [comment]
Yeah for sure — take it and run with it. :) I can merge back but don't feel like you need to submit pull requests. DHT would be really interesting to see though.

**Comment by deoxxa** [comment]
Awesome - I'll keep you posted and I'll let you know when I've gotten it to where I want it. Then you can pick and choose what you like from my changes :)

**Pull request merged**
